# Generated by Django 5.1.4 on 2025-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=30)),
                ('cnfpassword', models.TextField(max_length=30)),
                ('phoneno', models.BigIntegerField(max_length=10)),
                ('gender', models.TextField()),
                ('lang', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('group', models.TextField()),
            ],
        ),
    ]
