# Generated by Django 5.1.4 on 2025-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='phoneno',
            field=models.BigIntegerField(),
        ),
    ]
