# Generated by Django 5.1.4 on 2025-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0002_alter_details_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='last_donated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
