# Generated by Django 5.1.4 on 2025-06-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hands', '0003_details_last_donated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='last_donated',
        ),
    ]
